kind: AdaptiveDialog
autoEndDialog: true
triggers:
- type: OnBeginDialog
  actions:
  - SetProperty:
      property: conversation.topic
      value: invest
steps:
- intent: greeting
  recognizeType: regex
  patterns:
  - "(Hello|Hi there|Hey)"
  actions:
  - SetProperty:
      property: user.name
      value: null
  - SetProperty:
      property: user.investAmount
      value: 0
  - SetProperty:
      property: user.investType
      value: null
  - SetProperty:
      property: user.riskAppetite
      value: null
  - SetProperty:
      property: user.investOption
      value: null
  - SetProperty:
      property: user.continueInvest
      value: null
  - SetProperty:
      property: user.askedRisk
      value: false
  - SetProperty:
      property: user.askedAmount
      value: false
  - SetProperty:
      property: user.askedType
      value: false
  - SetProperty:
      property: user.askedOption
      value: false
  - BeginDialog:
      dialog: askName
- $id: askName
  steps:
  - userInput:
      alwaysPrompt: true
      property: user.name
      prompt: "What's your name?"
      validations:
      - type: string
  - SetProperty:
      property: user.askedRisk
      value: true
  - BeginDialog:
      dialog: askRiskAppetite
- $id: askRiskAppetite
  steps:
  - if:
      condition: "user.askedRisk == false"
      actions:
      - SetProperty:
          property: user.riskAppetite
          value: null
      - BeginDialog:
          dialog: askRiskAppetite
      elseActions:
      - TextInput:
          prompt: "How much risk are you comfortable with? (Low, Medium, High)"
          property: user.riskAppetite
          maxTurnCount: 2
- $id: recommendInvestment
  steps:
  - if:
      condition: "user.riskAppetite != null && user.askedAmount == false"
      actions:
      - SetProperty:
          property: user.askedAmount
          value: true
      - TextInput:
          prompt: "How much do you want to invest?"
          property: user.investAmount
          validations:
          - type: number
            minValue: 100
            maxValue: 1000000
          maxTurnCount: 2
      elseActions:
      - SetProperty:
          property: user.continueInvest
          value: false
      - BeginDialog:
          dialog: askContinueInvest
- $id: askContinueInvest
  steps:
  - if:
      condition: "user.continueInvest == false"
      actions:
      - SetProperty:
          property: user.investOption
          value: "None"
      - SendActivity:
          activity: "Thank you for considering investing with us. Have a great day!"
  - elseActions:
    - SetProperty:
        property: user.askedType
        value: true
    - ChoiceInput:
        prompt: "What type of investment are you interested in?"
        property: user.investType
        choices:
        - value: "Stocks"
          synonyms:
          - "Stock Market"
          - "Equities"
        - value: "Bonds"
          synonyms:
          - "Fixed Income"
        - value: "Mutual Funds"
          synonyms:
          - "Managed Funds"
          - "Funds"
- $id: finalizeInvestment
  steps:
  - if:
      condition: "user.askedType == true && user.askedOption == false"
      actions:
      - SetProperty:
          property: user.askedOption
          value: true
      - ChoiceInput:
          prompt: "Do you want us to recommend specific options within your chosen investment type?"
          property: user.investOption
          choices:
          - value: "Yes"
            synonyms:
            - "Sure"
            - "Of course"
          - value: "No"
            synonyms:
            - "No, thanks"
  - elseActions:
    - SendActivity:
        activity: "Great! We will provide you with the best investment options shortly. Thank you for choosing us!"
